import test from 'node:test';import assert from 'node:assert/strict';import{releaseGate}from'./release-gate.mjs';
const repo='instancelabs/example',head='a'.repeat(40),base='b'.repeat(40),merged='c'.repeat(40);
async function harness(overrides={}){
 const outputs={},requests=[];let merges=0,waits=0;
 const pr={number:1,state:'open',draft:false,changed_files:1,title:'fix: build',body:'<!-- jarvis-owner-repair:v1 -->',user:{login:'instance-labs-jarvis-repair[bot]',id:331706345},head:{sha:head,ref:'jarvis/fix-build',repo:{full_name:repo}},base:{ref:'main',repo:{full_name:repo}},mergeable:true,mergeable_state:'clean',labels:[],...overrides.pr};
 const run={id:9,status:'completed',conclusion:'success',event:'pull_request',head_sha:head,workflow_id:3,head_repository:{full_name:repo},...overrides.run};
 const result=await releaseGate({repo,config:{ciWorkflow:'checks.yml',check:'Quality',releaseMode:'aws'},event:{},eventName:'workflow_dispatch',number:1,ownerRequested:true,expectedSha:head,actor:'instance-labs-jarvis-repair[bot]',actorId:'331706345',waitAttempts:2,
 api:async(path,method='GET')=>{requests.push({path,method});if(path.endsWith('/pulls/1'))return pr;if(path.endsWith('/git/ref/heads/main'))return{object:{sha:base}};if(path.includes('/compare/'))return{behind_by:0,status:'ahead',...overrides.comparison};if(path.endsWith('/actions/workflows/checks.yml'))return{id:3};if(path.includes('/runs?'))return{workflow_runs:[run]};throw Error('Unexpected API '+path);},
 pages:async(path)=>path.includes('/jobs')?[{name:'Quality',status:'completed',conclusion:'success'}]:[{filename:'tsconfig.json',status:'modified',patch:'-x\n+y',...overrides.file}],content:async()=>{throw Error('Source repair must not read manifests')},merge:async({head:h,base:b})=>{assert.equal(h,head);assert.equal(b,base);merges++;return merged},pushRepair:async()=>{throw Error('No repair expected')},output:(k,v)=>outputs[k]=v,wait:async()=>{waits++;overrides.onWait?.(pr,run);},...overrides.params});
 return{result,outputs,merges,waits,requests};
}
test('owner source repair waits for exact checks then merges once and exposes immutable release SHA',async()=>{const r=await harness();assert.equal(r.merges,1);assert.equal(r.outputs.sha,merged);assert.equal(r.outputs.state,'merged');});
for(const [name,patch]of[['stale CI',{run:{head_sha:base}}],['behind main',{comparison:{behind_by:1}}],['forged author',{pr:{user:{login:'instance-labs-jarvis-repair[bot]',id:1}}}],['workflow diff',{file:{filename:'.github/workflows/deploy.yml'}}],['unknown actor',{params:{actor:'stranger'}}],['moved PR',{pr:{head:{sha:base}}}]])test('release gate holds '+name+' without merging',async()=>{const r=await harness(patch);assert.equal(r.merges,0);assert.equal(r.outputs.state,'held');assert(!r.outputs.sha);});
test('pending checks are bounded and produce a concrete hold',async()=>{const r=await harness({run:{status:'in_progress',conclusion:null}});assert.equal(r.waits,1);assert.equal(r.merges,0);assert.equal(r.outputs.state,'held');});
test('dry-run source release never merges',async()=>{const r=await harness({params:{dryRun:true}});assert.equal(r.merges,0);assert.equal(r.outputs.state,'eligible');});

test('explicit reviewed release accepts a human PR at the reviewed commit with all checks',async()=>{const r=await harness({pr:{user:{login:'TheLeePriest',id:24657363},body:'Feature reviewed by Lee'},file:{filename:'src/new-feature.ts'},params:{ownerReviewed:true}});assert.equal(r.merges,1);});
test('ordinary owner request does not imply human review of arbitrary PRs',async()=>{const r=await harness({pr:{user:{login:'TheLeePriest',id:24657363}}});assert.equal(r.merges,0);});
for(const [name,params,extra]of[['automatic event',{ownerRequested:false,ownerReviewed:true},{}],['unknown actor',{ownerReviewed:true,actor:'outsider'},{}],['changed commit',{ownerReviewed:true,expectedSha:base},{}],['failed CI',{ownerReviewed:true},{run:{conclusion:'failure'}}]])test('reviewed approval cannot bypass '+name,async()=>{const r=await harness({...extra,params});assert.equal(r.merges,0);assert.equal(r.outputs.state,'held');});

test('automatic releases wait for other required CI and then merge without human review',async()=>{const before={devDependencies:{vitest:'1.0.0'}},after={devDependencies:{vitest:'1.0.1'}};const oldLock={lockfileVersion:3,packages:{'':before}},newLock={lockfileVersion:3,packages:{'':after}};let reads=0;const r=await harness({pr:{user:{login:'dependabot[bot]',id:49699333},mergeable_state:'blocked',changed_files:2},onWait:pr=>pr.mergeable_state='clean',params:{ownerRequested:false,pages:async path=>path.includes('/jobs')?[{name:'Quality',status:'completed',conclusion:'success'}]:[{filename:'package.json',status:'modified'},{filename:'package-lock.json',status:'modified'}],content:async()=>[before,after,oldLock,newLock][reads++]}});assert.equal(r.waits,1);assert.equal(r.merges,1);assert.equal(r.outputs.state,'merged');});
test('automatic wait never bypasses checks that remain blocked',async()=>{const r=await harness({pr:{mergeable_state:'blocked'},params:{ownerRequested:false}});assert.equal(r.waits,1);assert.equal(r.merges,0);assert.equal(r.outputs.state,'held');});
