import test from 'node:test';import assert from 'node:assert/strict';
import {lockOnlyPolicy,ownerDependencyPolicy,sourceRepairPolicy,ownerRequestPolicy} from './release-policy.mjs';
import {dependencyPolicy,repairLockMetadata} from './policy.mjs';
const pkg=(v,dev=true)=>({version:v,dev,resolved:`https://registry.npmjs.org/js-yaml/-/js-yaml-${v}.tgz`,integrity:'sha512-YWJjZA=='}),manifest={name:'fixture',dependencies:{next:'15.5.21'},devDependencies:{vitest:'^4.1.10'}};
const lock=v=>({name:'fixture',lockfileVersion:3,packages:{'':structuredClone(manifest),'node_modules/js-yaml':pkg(v)}}),files=[{filename:'package-lock.json',status:'modified'}];
const verify=(a=lock('4.3.1'),b=lock('4.3.2'))=>dependencyPolicy(manifest,manifest,a,b,files);
test('automatic maintenance accepts existing dev-only lockfile security patches',()=>assert.deepEqual(verify(),['js-yaml']));
for(const [name,change]of[
 ['runtime package',b=>b.packages['node_modules/js-yaml'].dev=false],['major upgrade',b=>{b.packages['node_modules/js-yaml']=pkg('5.0.0');}],['script capability',b=>b.packages['node_modules/js-yaml'].hasInstallScript=true],['dependency edge',b=>b.packages['node_modules/js-yaml'].dependencies={evil:'*'}],['root metadata',b=>b.packages[''].scripts={install:'curl bad'}],['top metadata',b=>b.name='other'],['wrong registry identity',b=>b.packages['node_modules/js-yaml'].resolved='https://registry.npmjs.org/evil/-/evil-4.3.2.tgz'],['external registry',b=>b.packages['node_modules/js-yaml'].resolved='https://evil.test/a'],['missing package',b=>delete b.packages['node_modules/js-yaml']]]){
 test('lockfile-only gate rejects '+name,()=>{const b=lock('4.3.2');change(b);assert.throws(()=>verify(lock('4.3.1'),b));});
}
test('metadata repair restores only bundled peer/extraneous flags before revalidating real dependency changes',()=>{const a=lock('4.3.1'),b=lock('4.3.2'),path='node_modules/cdk/node_modules/semver';a.packages[path]={version:'7.8.5',inBundle:true,extraneous:true};b.packages[path]={version:'7.8.5',inBundle:true,peer:true};const r=repairLockMetadata(manifest,manifest,a,b,files);assert.deepEqual(r.paths,[path]);assert.deepEqual(r.lock.packages[path],a.packages[path]);assert.deepEqual(verify(a,r.lock),['js-yaml']);b.packages[path].version='7.8.6';assert.throws(()=>repairLockMetadata(manifest,manifest,a,b,files));});
test('owner-requested release accepts a stable runtime security patch, automatic release still holds it',()=>{const after=structuredClone(manifest);after.dependencies.next='15.5.25';const a=lock('4.3.1'),b=lock('4.3.1');a.packages['node_modules/next']={version:'15.5.21',resolved:'https://registry.npmjs.org/next/-/next-15.5.21.tgz',integrity:'sha512-YWJjZA=='};b.packages['']=after;b.packages['node_modules/next']={...a.packages['node_modules/next'],version:'15.5.25',resolved:'https://registry.npmjs.org/next/-/next-15.5.25.tgz'};const f=[...files,{filename:'package.json',status:'modified'}];assert.deepEqual(ownerDependencyPolicy(manifest,after,a,b,f),['next']);assert.throws(()=>dependencyPolicy(manifest,after,a,b,f));after.scripts={install:'curl evil'};assert.throws(()=>ownerDependencyPolicy(manifest,after,a,b,f));});
const pr={user:{login:'instance-labs-jarvis-repair[bot]',id:331706345},head:{sha:'a'.repeat(40),ref:'jarvis/fix-known-failure'},body:'<!-- jarvis-owner-repair:v1 -->'};
const source=[{filename:'tsconfig.json',status:'modified',patch:'-"types": ["vitest/globals"]\n+"types": ["vitest/globals", "node"]'}];
test('source release requires actual Jarvis App author and marker',()=>{assert.deepEqual(sourceRepairPolicy(pr,source),['tsconfig.json']);for(const patch of[{user:{...pr.user,id:1}},{body:'untrusted request'},{head:{ref:'other'}}])assert.throws(()=>sourceRepairPolicy({...pr,...patch},source));});
test('source release cannot smuggle workflows, infrastructure, credential files or manifest scripts',()=>{for(const filename of['.github/workflows/deploy.yml','AGENTS.md','lib/stack.ts','package.json','package-lock.json','src/credentials.json','.env','src/../safe.ts'])assert.throws(()=>sourceRepairPolicy(pr,[{...source[0],filename}]));});
test('release permission requires trusted dispatch identity and immutable head',()=>{ownerRequestPolicy('workflow_dispatch','TheLeePriest','24657363',pr.head.sha,pr);ownerRequestPolicy('workflow_dispatch','instance-labs-jarvis-repair[bot]',331706345,pr.head.sha,pr);for(const a of[['workflow_run','TheLeePriest','24657363',pr.head.sha],['workflow_dispatch','TheLeePriest','1',pr.head.sha],['workflow_dispatch','dependabot[bot]','49699333',pr.head.sha],['workflow_dispatch','TheLeePriest','24657363','b'.repeat(40)]])assert.throws(()=>ownerRequestPolicy(...a,pr));});
